from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Membuat stemmer sekali saja
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Custom stemming function to handle specific cases
def custom_stemming(word):
    exceptions = {
        "madam": "pemadam",  # Mengganti kata 'madam' menjadi 'pemadam'
        "pemilu": "pemilu",
        "kendaraan": "kendaraan",
        "pekerja": "pekerja",
        "tewas": "tewas",
        "timpa": "tertimpa",
        "laku": "melakukan",
        "jalan": "jalan",
        "mobil": "mobil",
        "truk": "truk",
        "warga": "warga",
        "bangunan": "bangunan",
        "polisi": "polisi",
        "desa": "desa",
        "camat": "camat",
        "kota": "kota",
        "periksa": "periksa",
        "sopir": "sopir",
        "bakar": "bakar",
        "meninggal": "meninggal",
        "rumah": "rumah",
        "tugas": "tugas",
        "lokasi": "lokasi",
        "celaka": "celaka",
        "sakit": "sakit",
        "diduga": "diduga",
        "luka": "luka",
        "akibat": "akibat",
        "api": "api",
        "alami": "alami",
        "langsung": "langsung",
        "jatuh": "jatuh",
        "kondisi": "kondisi",
        "terang": "terang",
        "lihat": "lihat",
        "proses": "proses",
        "nama": "nama",
        "masuk": "masuk",
        "tangan": "tangan",
        "mesin": "mesin",
        "salah": "salah",
        "usaha": "usaha",
        "gas": "gas",
        "keluarga": "keluarga",
        "ledak": "ledak",
        "pabrik": "pabrik",
        "kepala": "kepala",
        "insiden": "insiden",
        "lelah": "lelah",
        "buah": "buah",
        "nyata": "nyata",
        "kait": "kait",
        "suara": "suara",
        "kemudi": "kemudi",
        "rupa": "rupa",
        "senin": "senin",
        "gedung": "gedung",
        "setrum": "setrum",
        "gudang": "gudang",
        "jam": "jam",
        "tim": "tim",
        "polres": "polres",
        "sabtu": "sabtu",
        "anggota": "anggota",
        "barat": "barat",
        "rabu": "rabu",
        "jumat": "jumat",
        "tkp": "tkp",
        "kamis": "kamis",
        "aman": "aman",
        "tambang": "tambang",
        "longsor": "longsor",
        "selasa": "selasa",
        "pasang": "pasang",
        "arah": "arah",
        "alat": "alat",
        "lari": "lari",
        "unit": "unit",
        "bus": "bus",
        "rs": "rs",
        "sehat": "sehat",
        "minggu": "minggu",
        "turun": "turun",
        "lantai": "lantai",
        "timur": "timur",
        "motor": "motor",
        "tolong": "tolong",
        "informasi": "informasi",
        "kpu": "kpu",
        "tanah": "tanah",
        "cari": "cari",
        "bocor": "bocor",
        "kena": "kena",
        "bantu": "bantu",
        "malam": "malam",
        "meter": "meter",
        "damkar": "damkar",
        "pria": "pria",
        "kabel": "kabel",
        "pemadam": "pemadam",  # Menambahkan kata 'pemadam'
    }
    if word in exceptions:
        return exceptions[word]
    return stemmer.stem(word)
